# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('file_url', models.TextField(default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.TextField(default='')),
            ],
        ),
    ]
