# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('main_contact', models.CharField(blank=True, max_length=60)),
                ('main_contact_email', models.EmailField(blank=True, max_length=254)),
                ('street', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('zip', models.CharField(blank=True, max_length=11)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('company_email', models.EmailField(default='', max_length=254)),
                ('company_website', models.CharField(default='', max_length=60)),
                ('posting_link', models.CharField(default='', max_length=60)),
                ('position', models.CharField(default='', max_length=60)),
                ('response_date', models.DateField()),
                ('outcome', models.CharField(default='', max_length=60)),
                ('discovery_date', models.DateField()),
                ('application_sent', models.BooleanField(default=False)),
                ('interview_scheduled', models.BooleanField(default=False)),
                ('interview_location', models.CharField(blank=True, max_length=250)),
                ('interview_date', models.DateTimeField()),
                ('follow_up_date', models.DateField()),
                ('thank_you_note_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_steps', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', related_query_name='document', to='documents.Company'),
        ),
    ]
