# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20170307_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
